services:
  - type: worker
    name: delta-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    autoDeploy: true
    envVars:
      - key: DELTA_API_KEY
        sync: false
      - key: DELTA_API_SECRET
        sync: false
